marker_variant: full_15
paths:
  essential_genes_file: ./data/essential_genes_ensemble.csv
  figure_output: ./results/3_cco_results/dnase/full_15/imac
  marker_merged_file: ./results/2_basket_generation/dnase/dnase_15_cell_lines.csv
  results_folder: ./results/3_cco_results/dnase/full_15/imac
  rnaseq_file: ./data/rna_seq_processed/GSE220450_imac.txt
rna_seq_cell_type: imac
variables:
  marker_type: dnase
  output_file_name: gene_expression_plots
