marker_variant: 12_cell
paths:
  essential_genes_file: ./data/essential_genes_ensemble.csv
  figure_output: ./results/3_cco_results/h3k4me3/12_cell/adipocytes
  marker_merged_file: ./results/2_basket_generation/h3k4me3/h3k4me3_random_12_cell_lines.csv
  results_folder: ./results/3_cco_results/h3k4me3/12_cell/adipocytes
  rnaseq_file: ./data/rna_seq_processed/GSE249195_adipocytes.txt
rna_seq_cell_type: adipocytes
variables:
  marker_type: h3k4me3
  output_file_name: gene_expression_plots
