marker_variant: 5_cell
paths:
  essential_genes_file: ./data/essential_genes_ensemble.csv
  figure_output: ./results/3_cco_results/h3k4me3/5_cell/imac
  marker_merged_file: ./results/2_basket_generation/h3k4me3/h3k4me3_random_5_cell_lines.csv
  results_folder: ./results/3_cco_results/h3k4me3/5_cell/imac
  rnaseq_file: ./data/rna_seq_processed/GSE220450_imac.txt
rna_seq_cell_type: imac
variables:
  marker_type: h3k4me3
  output_file_name: gene_expression_plots
