marker_variant: full_15
paths:
  essential_genes_file: ./data/essential_genes_ensemble.csv
  figure_output: ./results/3_cco_results/h3k4me3/full_15/k7
  marker_merged_file: ./results/2_basket_generation/h3k4me3/h3k4me3_15_cell_lines.csv
  results_folder: ./results/3_cco_results/h3k4me3/full_15/k7
  rnaseq_file: ./data/rna_seq_processed/GSE220450_k7.txt
rna_seq_cell_type: k7
variables:
  marker_type: h3k4me3
  output_file_name: gene_expression_plots
